Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -76,3 +76,12 @@ jobs:
       # Verify SARIF Report Exists Before Upload
       - name: Verify SARIF Report Exists
         run: |
+          if [ ! -f gitleaks-report.sarif ]; then
+            echo "Error: SARIF report not found!"; exit 1;
+          fi
+
+      # Upload SARIF Report to GitHub Security Scanning
+      - name: Upload SARIF Report for Security Tab
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: gitleaks-report.sarif
